### ISSUE TITLE
Community resources for the Cardputer?

### ISSUE THREAD

**Issue by LEOcab** [m5stack/M5Cardputer-UserDemo#13]
I'm having a lot of fun tinkering with the Cardputer user demo. Are there any other community hangouts besides this official github?

The code and libraries all seem to be easy to read and well documented thus far. I'm looking for help with the logistical side of things, such as how to set up a proper dev/debug environment (instead of full clean/rebuild/reflash for every small change)

Thanks in advance!

**Comment by Forairaaaaa** [comment]
Hi, normally I write some [helper scripts](https://github.com/m5stack/M5Cardputer-UserDemo/blob/main/flash.sh) to do this. And there's no need to full clean for small changes, simply the `flash` command works~

**Comment by galileoleosolis** [comment]
Take a look at this
https://www.reddit.com/r/CardPuter/
