### ISSUE TITLE
Updating dependencies in components and utils

### ISSUE THREAD

**Issue by JohnZ03** [m5stack/M5Cardputer-UserDemo#15]
Noticed that this project uses other libraries but the files are directly copy pasted. Is there a way to know which version of each library is (especially for LovyanGFX and mooncake)? Or it is unecessary to consider upgrading those libs?

**Comment by Forairaaaaa** [comment]
But I think LovyanGFX and mooncake are quite the same to the main version, maybe some bug fixed.
